# Generated by Django 4.1.2 on 2022-11-02 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(default=None, max_length=100, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('user_phone', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('user_location', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('user_image', models.CharField(blank=True, default='static/userPanel/files/PNG/login_image.png', max_length=200, null=True)),
                ('password', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_creator', models.BooleanField(default=False)),
                ('is_visitor', models.BooleanField(default=False)),
                ('is_user', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=50)),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_details', models.TextField(max_length=1500)),
                ('blog_comment', models.CharField(max_length=500)),
                ('blog_image', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_person_name', models.CharField(max_length=50)),
                ('comm_person_email', models.EmailField(max_length=150)),
                ('comm_person_website', models.URLField()),
                ('comm_detils', models.TextField(max_length=500)),
                ('comm_date', models.DateField()),
                ('comm_time', models.TimeField()),
                ('comm_person_image', models.ImageField(upload_to='')),
                ('commnts_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userPanel.blogs')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='found',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fnd_title', models.CharField(max_length=200)),
                ('fnd_pragraph', models.CharField(max_length=200)),
                ('fnd_image', models.ImageField(upload_to='')),
                ('user', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fst_name', models.CharField(max_length=50)),
                ('lst_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('usr_email', models.CharField(max_length=50)),
                ('usr_pass', models.CharField(max_length=50)),
                ('is_staff', models.BooleanField(default=None)),
                ('is_active', models.BooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_title', models.CharField(max_length=200)),
                ('sl_pragraph', models.TextField(max_length=500)),
                ('sl_image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_phone', models.CharField(max_length=15)),
                ('user_location', models.CharField(max_length=100)),
                ('last_login', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tps_title', models.CharField(max_length=200)),
                ('tps_pragraph', models.TextField(max_length=500)),
                ('tps_line', models.CharField(max_length=200)),
                ('tps_file', models.FileField(upload_to='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=50)),
                ('sub_fee', models.CharField(max_length=50)),
                ('sub_duration', models.CharField(max_length=50)),
                ('sub_details', models.TextField(max_length=500)),
                ('sub_image', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rply_person_name', models.CharField(max_length=50)),
                ('rply_details', models.TextField(max_length=500)),
                ('rply_date', models.DateField()),
                ('rply_time', models.TimeField()),
                ('rply_person_image', models.ImageField(upload_to='')),
                ('rply_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userPanel.comments')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='guideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_title', models.CharField(max_length=200)),
                ('guid_pragraph', models.TextField(max_length=500)),
                ('guid_file', models.FileField(upload_to='')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=50)),
                ('feat_title', models.CharField(max_length=200)),
                ('feat_pragraph', models.TextField(max_length=500)),
                ('feat_duration', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('feat_fee', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('feat_image', models.FileField(default=None, max_length=250, upload_to='')),
                ('feat_cover', models.ImageField(default=None, max_length=250, upload_to='')),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('subject', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='userPanel.subjects')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('user_location', models.CharField(max_length=100)),
                ('user_image', models.CharField(blank=True, default='/static/userPanel/files/PNG/login_image.png', max_length=200, null=True)),
                ('last_login', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont_person_name', models.CharField(max_length=50)),
                ('cont_person_email', models.EmailField(max_length=150)),
                ('cont_person_subject', models.CharField(max_length=50)),
                ('cont_person_message', models.TextField(max_length=500)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=50)),
                ('com_pragraph', models.TextField(max_length=500)),
                ('com_address', models.CharField(max_length=150)),
                ('com_details', models.TextField(max_length=500)),
                ('com_image', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='all_feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feat_title', models.CharField(max_length=200)),
                ('feat_duration', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('feat_fee', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('feat_image', models.ImageField(upload_to='')),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('feature_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
