# Generated by Django 4.1.2 on 2022-11-02 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ByCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('course_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custmr_id', models.CharField(default=None, max_length=25)),
                ('dele_chrg', models.CharField(default=None, max_length=25)),
                ('shipper_name', models.CharField(default=None, max_length=50)),
                ('billing_name', models.CharField(default=None, max_length=50)),
                ('billing_adrs', models.CharField(default=None, max_length=50)),
                ('payment_method', models.CharField(default=None, max_length=50)),
                ('sub_total', models.CharField(default=None, max_length=25)),
                ('price', models.CharField(default=None, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='OrderTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.CharField(max_length=50)),
                ('prod_price', models.CharField(max_length=15)),
                ('prod_quantity', models.CharField(max_length=15)),
                ('mst_order_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('user_location', models.CharField(max_length=100)),
                ('user_image', models.CharField(blank=True, default='/static/userPanel/files/PNG/login_image.png', max_length=200, null=True)),
                ('last_login', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
